# Generated by Django 5.1 on 2024-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('started', 'Started'), ('completed', 'Completed')], default='inprogress', max_length=50),
        ),
    ]
